export const CATEGORIES = [
  "観光",
  "グルメ",
  "宿・ホテル",
  "自然",
  "アクティビティ",
  "歴史・文化",
  "その他",
] as const;

export const LOCATIONS = [
  "北海道",
  "青森県",
  "岩手県",
  "宮城県",
  "秋田県",
  "山形県",
  "福島県",
  "茨城県",
  "栃木県",
  "群馬県",
  "埼玉県",
  "千葉県",
  "東京都",
  "神奈川県",
  "新潟県",
  "富山県",
  "石川県",
  "福井県",
  "山梨県",
  "長野県",
  "岐阜県",
  "静岡県",
  "愛知県",
  "三重県",
  "滋賀県",
  "京都府",
  "大阪府",
  "兵庫県",
  "奈良県",
  "和歌山県",
  "鳥取県",
  "島根県",
  "岡山県",
  "広島県",
  "山口県",
  "徳島県",
  "香川県",
  "愛媛県",
  "高知県",
  "福岡県",
  "佐賀県",
  "長崎県",
  "熊本県",
  "大分県",
  "宮崎県",
  "鹿児島県",
  "沖縄県",
  "海外",
] as const;

export type Location = (typeof LOCATIONS)[number];

export const SORT_OPTIONS = [
  { value: "latest", label: "新着順" },
  { value: "popular", label: "人気順" },
] as const;

export const CATEGORY_ICONS: Record<string, string> = {
  観光: "🏛️",
  グルメ: "🍜",
  "宿・ホテル": "🏨",
  自然: "🌿",
  アクティビティ: "🎿",
  "歴史・文化": "⛩️",
  その他: "📍",
};

export const CATEGORY_COLORS: Record<string, string> = {
  観光: "bg-orange-50 text-orange-800",
  グルメ: "bg-amber-100 text-amber-800",
  "宿・ホテル": "bg-pink-100 text-pink-800",
  自然: "bg-green-100 text-green-800",
  アクティビティ: "bg-sky-100 text-sky-800",
  "歴史・文化": "bg-purple-100 text-purple-800",
  その他: "bg-slate-100 text-slate-600",
};
